services:
  rompetomp_inertia.inertia:
    class: Rompetomp\InertiaBundle\Service\Inertia
    public: false
    arguments:
      $engine: '@twig'
      $requestStack: '@request_stack'
      $serializer: '@serializer'
    calls:
      - setContainer: ['@service_container']

  Rompetomp\InertiaBundle\Service\InertiaInterface: '@rompetomp_inertia.inertia'

  rompetomp_inertia.gateway:
    class: Rompetomp\InertiaBundle\Ssr\HttpGateway
    arguments:
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $inertia: '@rompetomp_inertia.inertia'

  Rompetomp\InertiaBundle\Ssr\GatewayInterface: '@rompetomp_inertia.gateway'

  rompetomp_inertia.twig_extension:
    class: Rompetomp\InertiaBundle\Twig\InertiaExtension
    public: false
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $gateway: '@rompetomp_inertia.gateway'
    tags:
      - { name: twig.extension }

  Rompetomp\InertiaBundle\EventListener\InertiaListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.response }
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $debug: '%kernel.debug%'
